<?php

namespace Plugins\Letter\Notifications;

use Illuminate\Auth\Notifications\VerifyEmail as VerifyEmailBase;
use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Messages\MailMessage;

class LetterEmailNotification extends VerifyEmailBase
{
    use Queueable;

    protected $recipient;
    protected $data;
    protected $general_settings;
    protected $authUser;

    public function __construct($recipient, $data)
    {
        $this->recipient = $recipient;
        $this->data = $data;
        $this->general_settings = get_settings('general_settings');
        $this->authUser = getAuthenticatedUser();
    }

    /**
     * Get the notification's delivery channels.
     */
    public function via($notifiable): array
    {
        return ['mail'];
    }

    /**
     * Get the mail representation of the notification.
     */
    public function toMail($notifiable)
    {
        $full_logo_path = ! isset($this->general_settings['full_logo']) || empty($this->general_settings['full_logo']) ? 'logos/default_full_logo.png' : $this->general_settings['full_logo'];
        $full_logo_url = asset('storage/' . $full_logo_path);

        $subject = $this->getSubject();
        $content = $this->getContent();

        $mailMessage = (new MailMessage())
            ->view('mail.html', ['content' => $content, 'logo_url' => $full_logo_url])
            ->subject($subject);

        // Attach PDF if provided
        if (isset($this->data['pdf'])) {
            $filename = str_replace(' ', '_', $this->data['letter']->title) . '_' . $this->data['letter']->employee->name . '.pdf';
            $mailMessage->attachData(
                $this->data['pdf']->output(),
                $filename,
                ['mime' => 'application/pdf']
            );
        }

        return $mailMessage;
    }

    /**
     * Get the array representation of the notification.
     */
    public function toArray($notifiable): array
    {
        return [
            'letter_id' => $this->data['letter']->id,
            'subject' => $this->getSubject(),
            'sent_at' => now(),
        ];
    }

    /**
     * Get email subject
     */
    protected function getSubject()
    {
        return $this->data['subject'] ?? 'Letter from ' . ($this->general_settings['company_title'] ?? config('app.name'));
    }

    /**
     * Get email content with letter details
     */
    protected function getContent()
    {
        $message = $this->data['message'] ?? '';
        $letter = $this->data['letter'];
        $workspace_name = $this->authUser->workspace->company_name ?? $this->authUser->workspace->name ?? '';

        $content = "
            <div style='font-family: Arial, sans-serif; line-height: 1.6; color: #333;'>
                {COMPANY_LOGO}

                <div style='margin: 30px 0;'>
                    <h2 style='color: #2c3e50; margin-bottom: 20px;'>Letter: {$letter->title}</h2>

                    <div style='background: #f8f9fa; padding: 15px; border-left: 4px solid #007bff; margin: 20px 0;'>
                        <p><strong>Employee:</strong> {$letter->employee->name}</p>
                        <p><strong>Date:</strong> " . \Carbon\Carbon::parse($letter->letter_date)->format('d M Y') . "</p>
                        <p><strong>Generated by:</strong> {$letter->createdBy->name}</p>
                    </div>";

        if (! empty($message)) {
            $content .= "
                    <div style='margin: 20px 0;'>
                        <h3 style='color: #34495e;'>Message:</h3>
                        <p>" . nl2br(e($message)) . '</p>
                    </div>';
        }

        $content .= "
                    <div style='margin: 30px 0;'>
                        <p>Please find the letter attached as a PDF document.</p>
                    </div>

                    <div style='margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee;'>
                        <p style='color: #666; font-size: 14px;'>
                            Best regards,<br>
                            <strong>{$workspace_name}</strong>
                        </p>
                    </div>
                </div>
            </div>";

        return $content;
    }
}
